#!/usr/bin/env python3
from __future__ import annotations

import json
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import urlparse


ROOT = Path(__file__).resolve().parent
OBSIDIAN_VAULT = Path("/Users/shafeer/Downloads/iFeed-AI-OS-Obsidian-Vault")
OBSIDIAN_SIGNAL_ROOT = OBSIDIAN_VAULT / "15 iFeed Master Platform" / "08 Weekly Signal Management"
ALLOWED_TOOLS = {
    "codex",
    "chatgpt",
    "claude",
    "perplexity",
    "deepseek",
    "gemini",
    "miscellaneous",
}


def validate_week_tool(week: str, tool: str) -> None:
    if not week.startswith("w") or not week[1:].isdigit():
        raise ValueError("Invalid week")
    if tool not in ALLOWED_TOOLS:
        raise ValueError("Invalid tool")


def raw_path(week: str, tool: str) -> Path:
    validate_week_tool(week, tool)
    return ROOT / "weeks" / week / "raw" / f"{tool}_output.md"


def obsidian_week_dir(week: str) -> Path:
    if not week.startswith("w") or not week[1:].isdigit():
        raise ValueError("Invalid week")
    return OBSIDIAN_SIGNAL_ROOT / week.upper()


def obsidian_raw_path(week: str, tool: str) -> Path:
    validate_week_tool(week, tool)
    return obsidian_week_dir(week) / "01 Raw Captures" / f"{tool}_output.md"


def ensure_obsidian_week_workspace(week: str) -> None:
    base = obsidian_week_dir(week)
    folders = [
        "01 Raw Captures",
        "02 Refined Register",
        "03 Private Dashboard",
        "04 Selection and Editorial Review",
        "05 Cockpit Handoff",
        "06 Publish Database",
        "07 Notes and Decisions",
    ]
    for folder in folders:
        (base / folder).mkdir(parents=True, exist_ok=True)
    index = base / "00 Week Workspace.md"
    index.write_text(
        "\n".join(
            [
                "---",
                f'title: "{week.upper()} Signal Management Workspace"',
                "type: weekly-signal-management",
                f"week: {week.upper()}",
                "---",
                "",
                f"# {week.upper()} Signal Management Workspace",
                "",
                "This workspace is generated by the iFeed Signal Management System.",
                "",
                "## Workflow",
                "",
                "- [[01 Raw Captures]]",
                "- [[02 Refined Register]]",
                "- [[03 Private Dashboard]]",
                "- [[04 Selection and Editorial Review]]",
                "- [[05 Cockpit Handoff]]",
                "- [[06 Publish Database]]",
                "- [[07 Notes and Decisions]]",
                "",
                "## Raw Capture Files",
                "",
                *[f"- [[01 Raw Captures/{tool}_output|{tool} output]]" for tool in sorted(ALLOWED_TOOLS)],
                "",
            ]
        ),
        encoding="utf-8",
    )


class Handler(SimpleHTTPRequestHandler):
    def end_headers(self) -> None:
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        super().end_headers()

    def do_OPTIONS(self) -> None:
        self.send_response(204)
        self.end_headers()

    def do_POST(self) -> None:
        route = urlparse(self.path).path
        try:
            length = int(self.headers.get("Content-Length", "0"))
            payload = json.loads(self.rfile.read(length).decode("utf-8"))
            if route == "/api/write-raw":
                result = self.write_raw(payload)
            elif route == "/api/write-all-raw":
                result = self.write_all_raw(payload)
            else:
                self.send_error(404, "Unknown API route")
                return
            self.respond_json(200, result)
        except Exception as exc:  # noqa: BLE001
            self.respond_json(400, {"ok": False, "error": str(exc)})

    def write_raw(self, payload: dict) -> dict:
        week = str(payload.get("week", "w25"))
        tool = str(payload.get("tool", ""))
        content = str(payload.get("content", "")).strip()
        if not content:
            raise ValueError("No raw output content to write")
        path = raw_path(week, tool)
        path.parent.mkdir(parents=True, exist_ok=True)
        body = f"# {week.upper()} {tool} output\n\n{content}\n"
        path.write_text(body, encoding="utf-8")
        ensure_obsidian_week_workspace(week)
        obsidian_path = obsidian_raw_path(week, tool)
        obsidian_path.parent.mkdir(parents=True, exist_ok=True)
        obsidian_path.write_text(body, encoding="utf-8")
        return {
            "ok": True,
            "path": str(path),
            "obsidian_path": str(obsidian_path),
            "bytes": len(body.encode("utf-8")),
        }

    def write_all_raw(self, payload: dict) -> dict:
        week = str(payload.get("week", "w25"))
        outputs = payload.get("outputs", {})
        if not isinstance(outputs, dict):
            raise ValueError("outputs must be an object keyed by tool")
        written = []
        for tool, content in outputs.items():
            text = str(content).strip()
            if not text:
                continue
            result = self.write_raw({"week": week, "tool": tool, "content": text})
            written.append(result)
        if not written:
            raise ValueError("No non-empty raw outputs to write")
        return {"ok": True, "written": written}

    def respond_json(self, status: int, payload: dict) -> None:
        data = json.dumps(payload, indent=2).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)


def main() -> None:
    server = ThreadingHTTPServer(("127.0.0.1", 8793), Handler)
    print(f"iFeed signal writer running at http://127.0.0.1:8793/")
    print(f"Serving and writing inside: {ROOT}")
    print(f"Obsidian signal workspace: {OBSIDIAN_SIGNAL_ROOT}")
    server.serve_forever()


if __name__ == "__main__":
    main()
